#!/bin/bash

sudo apt install -y libcurses-ocaml-dev libudev-dev libdrm-dev

cd '/home/user/Software'
git clone 'https://github.com/Syllo/nvtop.git'
cd nvtop && mkdir build && cd build
cmake ..
make -j
sudo make install
