#!/bin/bash

if [[ -n $(which python3.10) ]]
then
    echo 'python3.10 is already installed.'
else
    sudo apt update
    sudo apt install software-properties-common -y
    sudo add-apt-repository ppa:deadsnakes/ppa
    sudo apt install -y python3.10 python3.10-distutils

    curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10

    python3.10 -m pip install -U pip virtualenv
fi
